# Generated by Django 4.0.7 on 2022-12-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='user_id',
        ),
    ]
