# Generated by Django 4.0.7 on 2022-12-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_user_album_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user_id',
            new_name='user',
        ),
    ]
