# Generated by Django 4.0.7 on 2022-12-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_user_id_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='user_id',
        ),
    ]
